Fix cargo's test on *nix link OS
Unix link OS distinguish between filename case. The test fails because the
filename used in the test are different in case. This changes the case of
the filename to lower case.

---
--- FAIL: TestParse (0.00s)
    --- FAIL: TestParse/cargo_normal.lock (0.00s)
        parse_test.go:37: Open() error: open testdata/cargo_normal.lock: no such file or directory
    --- FAIL: TestParse/cargo_many.lock (0.00s)
        parse_test.go:37: Open() error: open testdata/cargo_many.lock: no such file or directory
    --- FAIL: TestParse/cargo_nickel.lock (0.00s)
        parse_test.go:37: Open() error: open testdata/cargo_nickel.lock: no such file or directory
FAIL
FAIL   github.com/knqyf263/go-dep-parser/pkg/cargo     0.016s
---

Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>